const data = {
  products: [
    {
      name: "Samsung Galaxy J7",
      slug: "samsung_galaxy_j7",
      category: "mobile",
      image: "/images/m1.jpg",
      new_price: 200.0,
      old_price: 400.0,
      description: "high quality shirt",
    },
    {
      name: "OPPO A37f",
      slug: "oppo_a37f",
      category: "mobile",
      image: "/images/m2.jpg",
      new_price: 2000.0,
      old_price: 4000.0,
      description: "high quality shirt",
    },
    {
      name: "Apple iPhone X",
      slug: "apple_iphone_x",
      category: "mobile",
      image: "/images/m3.jpg",
      new_price: 20000.0,
      old_price: 40000.0,
      description: "high quality shirt",
    },
    {
      name: "Sony 80 cm (32 inches)",
      slug: "sony_80_cm",
      category: "tv_and_audio",
      image: "/images/m4.jpg",
      new_price: 11500.0,
      old_price: 45000.0,
      description: "high quality shirt",
    },
    {
      name: "Artis Speaker",
      slug: "artis_apeaker",
      category: "tv_and_audio",
      image: "/images/m5.jpg",
      new_price: 3002.0,
      old_price: 4002.0,
      description: "high quality shirt",
    },
    {
      name: "Philips Speakers",
      slug: "philips_speakers",
      category: "tv_and_audio",
      image: "/images/m6.jpg",
      new_price: 2200.0,
      old_price: 4400.0,
      description: "high quality shirt",
    },
    {
      name: "Whirlpool 245",
      slug: "whirlpoop_245",
      category: "large_appliance",
      image: "/images/m7.jpg",
      new_price: 18000.0,
      old_price: 40000.0,
      description: "high quality shirt",
    },
    {
      name: "BPL Washing Machine",
      slug: "bpl_washing_machine",
      category: "large_appliance",
      image: "/images/m8.jpg",
      new_price: 22400.0,
      old_price: 44300.0,
      description: "high quality shirt",
    },
    {
      name: "Microwave Oven",
      slug: "microwave_oven",
      category: "large_appliance",
      image: "/images/m9.jpg",
      new_price: 20000.0,
      old_price: 40000.0,
      description: "high quality shirt",
    },
  ],
};

export default data;
